"""Flight scheduling package — planning, spawn, live ops, ferry."""
from __future__ import annotations

from engine.scheduling.shared import (
    DAY_START_HOURS,
    _assert_player_routes_schedulable,
    get_financial_constant,
    _flight_fuel_gallons,
    _assert_new_segment_airport_limits,
)
from engine.scheduling.time_helpers import (
    week_base_hours,
    calendar_game_week_from_state,
    hhmm_from_absolute_game_hour,
    _day_of_week_label,
)
from engine.scheduling.rotation import (
    route_ids_from_airport_chain,
    format_rotation_airport_chain,
    normalize_tail_schedule_for_week,
    assert_tail_schedule_accepts_new_intervals,
    _flight_number_suffix_for_tail_week,
    merge_quick_weekly_template,
    _initial_airport_before_first_event,
    validate_position_timeline_for_new_legs,
    merge_detailed_weekly_template,
    normalize_turn_minutes,
    assign_rotation,
    _operating_days_list,
    _plan_chained_detailed_segments,
    _detailed_chained_chains_list_from_blob,
    _reject_if_incompatible_weekly_template_for_chained,
    create_chained_detailed_rotation,
    create_flight_schedule,
)
from engine.scheduling.segments import (
    reset_operational_schedule_for_new_calendar_week,
    remove_superseded_scheduled_segments_for_tail,
    _spawn_simple_rotation_legs,
    _spawn_detailed_template_week,
    _spawn_one_detailed_chained_chain,
    _spawn_detailed_chained_template_week,
    spawn_rotation_segments_for_week,
    _per_leg_demand_from_weekly_pool,
    route_weekly_passenger_accounting,
)
from engine.scheduling.flight_ops import (
    propagate_delay,
    check_mtt_violation,
    on_departure,
    on_arrival,
    get_flight_events_between,
    get_all_flights,
    get_tail_flight_segments_for_week,
)
from engine.scheduling.ferry import (
    max_weekly_airborne_hours_cap,
    sum_airborne_hours_for_tail_week,
    get_tail_weekly_utilization,
    route_ops_summaries_for_week,
    route_current_schedule_summary,
    _ensure_catalog_route,
    tail_position_and_free_hour,
    schedule_ferry_reposition,
    schedule_ferry_to_hub,
    cancel_rotation,
)

__all__ = [
    "DAY_START_HOURS",
    "get_financial_constant",
    "week_base_hours",
    "calendar_game_week_from_state",
    "hhmm_from_absolute_game_hour",
    "route_ids_from_airport_chain",
    "format_rotation_airport_chain",
    "reset_operational_schedule_for_new_calendar_week",
    "normalize_tail_schedule_for_week",
    "max_weekly_airborne_hours_cap",
    "remove_superseded_scheduled_segments_for_tail",
    "sum_airborne_hours_for_tail_week",
    "get_tail_weekly_utilization",
    "route_ops_summaries_for_week",
    "route_current_schedule_summary",
    "assert_tail_schedule_accepts_new_intervals",
    "merge_quick_weekly_template",
    "validate_position_timeline_for_new_legs",
    "merge_detailed_weekly_template",
    "normalize_turn_minutes",
    "assign_rotation",
    "propagate_delay",
    "check_mtt_violation",
    "create_chained_detailed_rotation",
    "spawn_rotation_segments_for_week",
    "route_weekly_passenger_accounting",
    "on_departure",
    "on_arrival",
    "get_flight_events_between",
    "get_all_flights",
    "get_tail_flight_segments_for_week",
    "tail_position_and_free_hour",
    "schedule_ferry_reposition",
    "schedule_ferry_to_hub",
    "cancel_rotation",
    "create_flight_schedule",
    "_day_of_week_label",
    "_plan_chained_detailed_segments",
]
